### ISSUE TITLE
想请问下用什么设备训练的，训练了多长时间？

### ISSUE THREAD

**Issue by ChenzhengUESTC** [TsinghuaAI/CPM-Generate#1]
RT 3x

**Comment by zzy14** [comment]
使用了8台8卡V100，训练时间约为两周，我们之后会提供技术报告，里面会有具体的细节 :)

**Comment by bigprince97** [comment]
请问下，训练该模型时是否用到了微软的deepspeed框架

**Comment by zzy14** [comment]
@bigprince97 初步使用了deepspeed，实验里观察对于显存有比较明显的减少。

**Comment by thesby** [comment]
@zzy14 请问使用什么数据集训练的呢？是公开数据集还是私有的数据集呢？

**Comment by zzy14** [comment]
@thesby 谢谢您的关注！部分是公开数据部分是私有的，考虑到版权问题我们不会开源这批数据。
