### ISSUE TITLE
TypeError: Class advice impossible in Python3.  Use the @implementer class decorator instead.

### ISSUE THREAD

**Issue by zhaogangthu** [TsinghuaAI/CPM-Generate#10]
from apex.normalization.fused_layer_norm import FusedLayerNorm as LayerNorm

请问是python版本的问题吗？我在win10下运行不了。

**Comment by JJack0812** [comment]
linux python3.6也出现了这个问题。

**Comment by zzy14** [comment]
可以试一试更新在README里的docker环境。
