### ISSUE TITLE
结果无法复现

### ISSUE THREAD

**Issue by leecuijiao** [TsinghuaAI/CPM-Generate#11]
请问这篇智源研究院发布的文章 https://mp.weixin.qq.com/s/QinmwLIRfYL9N2LfoFoEBQ 中提到的样例展示的第一个，用模型预测的结果不对，需要特殊的拼接方式或者需要微调吗
![image](https://user-images.githubusercontent.com/17920817/99789088-09205980-2b5d-11eb-8c3c-22645adb89b1.png)

**Comment by FannierPeng** [comment]
@leecuijiao 在运行generate_text.sh时我遇到这个错误？请问你有遇到过吗？怎么解决的？谢谢！

-----------------------------
Generate Samples
Generate Samples
WARNING: No training data specified
WARNING: No training data specified
using world size: 2 and model-parallel size: 2 
 > using dynamic loss scaling
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 249, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'generate_samples.py', '--local_rank=1', '--model-parallel-size', '2', '--num-layers', '32', '--hidden-size', '2560', '--load', '/gdata/ChineseCorpus/CPM-model-v1', '--num-attention-heads', '32', '--seq-length', '1024', '--max-position-embeddings', '1024', '--fp16', '--cache-dir', 'cache', '--out-seq-length', '512', '--temperature', '0.9', '--top_k', '0', '--top_p', '0', '--tokenizer-path', 'bpe_3w_new/', '--vocab-size', '30000']' died with <Signals.SIGSEGV: 11>.
----------------------------------

**Comment by FannierPeng** [comment]
> @leecuijiao 在运行generate_text.sh时我遇到这个错误？请问你有遇到过吗？怎么解决的？谢谢！
> 
> Generate Samples
> Generate Samples
> WARNING: No training data specified
> WARNING: No training data specified
> using world size: 2 and model-parallel size: 2
> 
> > using dynamic loss scaling
> > Traceback (most recent call last):
> > File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
> > "**main**", mod_spec)
> > File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
> > exec(code, run_globals)
> > File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 253, in 
> > main()
> > File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 249, in main
> > cmd=cmd)
> > subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'generate_samples.py', '--local_rank=1', '--model-parallel-size', '2', '--num-layers', '32', '--hidden-size', '2560', '--load', '/gdata/ChineseCorpus/CPM-model-v1', '--num-attention-heads', '32', '--seq-length', '1024', '--max-position-embeddings', '1024', '--fp16', '--cache-dir', 'cache', '--out-seq-length', '512', '--temperature', '0.9', '--top_k', '0', '--top_p', '0', '--tokenizer-path', 'bpe_3w_new/', '--vocab-size', '30000']' died with <Signals.SIGSEGV: 11>.

@zzy14

**Comment by zzy14** [comment]
@leecuijiao 不需要微调，我们汇报的例子是来源于实现的一个demo，demo的是现实随机生成多个预测结果，然后每个预测结果在换行符、句号、逗号进行阶段。

**Comment by zzy14** [comment]
@FannierPeng 我也没遇到过你这个错，我们会在近期准备一个docker。

**Comment by leecuijiao** [comment]
@zzy14 拼接方式会影响结果吗，汇报中的demo是使用的什么拼接方式呢

**Comment by ZhuJingdan** [comment]
> > @leecuijiao 在运行generate_text.sh时我遇到这个错误？请问你有遇到过吗？怎么解决的？谢谢！
> > Generate Samples
> > Generate Samples
> > WARNING: No training data specified
> > WARNING: No training data specified
> > using world size: 2 and model-parallel size: 2
> > > using dynamic loss scaling
> > > Traceback (most recent call last):
> > > File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
> > > "**main**", mod_spec)
> > > File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
> > > exec(code, run_globals)
> > > File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 253, in
> > > main()
> > > File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 249, in main
> > > cmd=cmd)
> > > subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'generate_samples.py', '--local_rank=1', '--model-parallel-size', '2', '--num-layers', '32', '--hidden-size', '2560', '--load', '/gdata/ChineseCorpus/CPM-model-v1', '--num-attention-heads', '32', '--seq-length', '1024', '--max-position-embeddings', '1024', '--fp16', '--cache-dir', 'cache', '--out-seq-length', '512', '--temperature', '0.9', '--top_k', '0', '--top_p', '0', '--tokenizer-path', 'bpe_3w_new/', '--vocab-size', '30000']' died with <Signals.SIGSEGV: 11>.
> 
> @zzy14

请问你解决了吗，我也碰到了你这个问题

**Comment by zzy14** [comment]
@leecuijiao 会一定程度影响结果，拼接方式就是推送里写的那样，每个输入一行。另外，模型的生成结果是随机采样的，所以也没法保证每次都生成一样的。
