### ISSUE TITLE
2路模型并行的参数，转换到4路模型？

### ISSUE THREAD

**Issue by bigprince97** [TsinghuaAI/CPM-Generate#13]
你好，我想基于这模型在自己的数据集做finetuing，但是在3090上只能将模型分在4个gpu训练，无法像在预训练那样将模型分到2个gpu，所以需要将参数合并，并在某些层均分层4份，并保存，这种做法可以吗？

**Comment by zzy14** [comment]
理论上是可以的，按照Megatron的并行思路，每一层都要均分成4份，这一点你可能需要注意一下。

**Comment by bigprince97** [comment]
转化成功了，谢谢

**Comment by zhenhao-huang** [comment]
> 转化成功了，谢谢



> 你好，我想基于这模型在自己的数据集做finetuing，但是在3090上只能将模型分在4个gpu训练，无法像在预训练那样将模型分到2个gpu，所以需要将参数合并，并在某些层均分层4份，并保存，这种做法可以吗？

 @你好，您finetuing的时候每个gpu占用多大的显存，能进一步缩小吗（经费紧缺= =）

**Comment by bigprince97** [comment]
24g显存，模型分在4个gpu上，batch size设为12-16之间，可以塞满显存

**Comment by bigprince97** [comment]
进一步缩小可以调整deepspeed的参数试试

**Comment by zhenhao-huang** [comment]
> 进一步缩小可以调整deepspeed的参数试试

好的，谢谢。可以看下你是怎么微调吗

**Comment by bigprince97** [comment]
我的deepspeed参数是开启fp16和zero_optimization, stage设为2，以及activation_checkoint，如果打开cpu_offload应该还可以增加batch size，不过没有试过。

**Comment by zmingshi** [comment]
@bigprince97 麻烦问下，你finetune 的是什么任务呢？我想finetune 一个文本生成任务，不知道参数都怎么配置，求指教～

**Comment by bigprince97** [comment]
使用医学领域的数据finetuing，主要是想利用模型的one shot能力。使用一般的训练gpt2的参数设置就可以，我并没有进行过多调整，学习率4e-4，warm up ratio 0.01，batch size 96, 不过因为模型较大，需要分模型在多个gpu上训练，使用megatron+deepspeed训练。

**Comment by zhenhao-huang** [comment]
@bigprince97 调小batch的话，应该可以在两张3090上微调吧？

**Comment by bigprince97** [comment]
可以的

**Comment by zhenhao-huang** [comment]
@bigprince97 您的3090是什么环境呢，我的python 3.6.8，torch 1.7.1+cu110，会报ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory这样的错

**Comment by zhenhao-huang** [comment]
解决了，是apex问题

**Comment by zhenhao-huang** [comment]
@bigprince97 解决了，是apex问题，但是用pytorch1.7,1微调又会报其它问题

**Comment by zhenhao-huang** [comment]
@bigprince97 最后使用了pytorch的Preview (Nightly)版本解决此问题。我想问下您的4张3090是怎么搭建的，是插在一个主机上还是一个服务器上使用，我打算再入2张3090，但是目前我的一个主机只能插2张3090。

**Comment by zhenhao-huang** [comment]
@bigprince97 方便留下您的联系方式交流吗

**Comment by Tron1994** [comment]
请问有转化脚本吗，官方提供的change_mp.py脚本转换后加载，会报错：
size mismatch for lm_head.weight: copying a param with shape torch.Size([6560, 2048]) from checkpoint, the shape in current model is torch.Size([3280, 4096]).
