### ISSUE TITLE
请问可以在windows上运行吗

### ISSUE THREAD

**Issue by ArlanCooper** [TsinghuaAI/CPM-Generate#14]
请问可以在windows上运行吗

**Comment by zzy14** [comment]
没有测试过，但如果windows对torch支持比较好的话我感觉应该没啥问题。

**Comment by ArlanCooper** [comment]
> 没有测试过，但如果windows对torch支持比较好的话我感觉应该没啥问题。
好的，谢谢，请问是否方便也写一份windows的帮助文档呢

**Comment by zzy14** [comment]
好的，我们手头上暂时没有windows的机器，未来争取尽早完成windows的测试，感谢你的关注！
