### ISSUE TITLE
模型能够背诵很多古文，甚至是朱自清的背影，请问一下是因为训练语料中这些文章重复了很多次吗？

### ISSUE THREAD

**Issue by bigprince97** [TsinghuaAI/CPM-Generate#21]
![image](https://user-images.githubusercontent.com/51944774/101228742-f880ef00-36d7-11eb-9dac-8e71a2d52dcc.png)

**Comment by bigprince97** [comment]
预训练语料里是不是做一下去重，效果会更好？

**Comment by bigprince97** [comment]
![image](https://user-images.githubusercontent.com/51944774/101228809-3bdb5d80-36d8-11eb-9690-5d6db388712c.png)

**Comment by zzy14** [comment]
感谢您的建议！之后我们会对数据做更精细的处理。现在有一些工作也说了大模型的拟合能力可能很强（ https://arxiv.org/abs/2012.07805 ），比如您提到的生成原文的问题。
