### ISSUE TITLE
测试使用命令bash scripts/generate_text.sh /path/to/CPM example.txt报错

### ISSUE THREAD

**Issue by zhenhao-huang** [TsinghuaAI/CPM-Generate#22]
Generate Samples
WARNING: No training data specified
Generate Samples
WARNING: No training data specified
using world size: 2 and model-parallel size: 2 
->using dynamic loss scaling
Traceback (most recent call last):
  File "/content/CPM-Generate/generate_samples.py", line 379, in <module>
    main()
  File "/content/CPM-Generate/generate_samples.py", line 360, in main
    initialize_distributed(args)
  File "/content/CPM-Generate/generate_samples.py", line 96, in initialize_distributed
    device = args.rank % torch.cuda.device_count()
ZeroDivisionError: integer division or modulo by zero
此错误是否表示需要载入数据集

**Comment by zzy14** [comment]
`device = args.rank % torch.cuda.device_count()`应该是说你没有指定cuda的显卡。

**Comment by zhenhao-huang** [comment]
> `device = args.rank % torch.cuda.device_count()`应该是说你没有指定cuda的显卡。

怎么指定cuda显卡

**Comment by zzy14** [comment]
在运行命令前加上环境变量 `CUDA_VISIBLE_DEVICES=xxx` xxx是需要指定卡的标号

**Comment by zhenhao-huang** [comment]
> 在运行命令前加上环境变量 `CUDA_VISIBLE_DEVICES=xxx` xxx是需要指定卡的标号

明白了，这是单卡的时候会报错，双卡就不会，但是似乎单双卡都会这样的警告
Generate Samples
WARNING: No training data specified
Generate Samples
WARNING: No training data specified
是需要加载数据吗

**Comment by zhenhao-huang** [comment]
生成不需要加载数据，微调、训练则需要
