### ISSUE TITLE
模型链接无法下载

### ISSUE THREAD

**Issue by zsf123456** [TsinghuaAI/CPM-Generate#23]
模型链接无法下载
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<RequestId>5FCDA4DADF97EB3138AD1144</RequestId>
<HostId>baai-work-assets.oss-cn-beijing.aliyuncs.com</HostId>
<Key>cpm/model-v1.tar.gz</Key>
</Error>

**Comment by zzy14** [comment]
我们更新了一下模型下载的路径 您可以先通过 https://work-assets.baai.ac.cn/cpm/model-v2.tar 下载。

**Comment by mengmengmengmeng1234** [comment]
> 我们更新了一下模型下载的路径 您可以先通过 https://work-assets.baai.ac.cn/cpm/model-v2.tar 下载。

下载时报You don't have permission to access the URL on this server.

**Comment by zzy14** [comment]
貌似不能从github直接下载🤣，要走 https://cpm.baai.ac.cn/download.html，但现在地址还未更新，今天应该会完成更新。

**Comment by zsf123456** [comment]
好哒，感谢。等模型更新好了，可以告诉我下吗？

**Comment by zzy14** [comment]
已经可以下载了~
