### ISSUE TITLE
模型生成的内容过长

### ISSUE THREAD

**Issue by zhizeng8** [TsinghuaAI/CPM-Generate#24]
![image](https://user-images.githubusercontent.com/49787234/101567162-44e76a00-3a0b-11eb-8045-553d27386dbd.png)
图中模型生成的内容正常吗？怎样让他在恰当的时候停止呢？

**Comment by zhizeng8** [comment]
而且美国的首都应该是华盛顿而不是纽约吧？哈哈

**Comment by zzy14** [comment]
这里预先设定了一个最大输出长度，模型会一直生成到满足条件，您可以修改这个长度或者在代码里加入一些判断条件来在恰当的时候退出。另外生成的时候是随机采样的，所以有可能生成出违反常识的表述🤣之前的工作发现如果不做随机采样，每次都选概率最高的容易出一些奇怪的生成结果。

**Comment by zhizeng8** [comment]
好的，谢谢！
