### ISSUE TITLE
模型版本

### ISSUE THREAD

**Issue by mikezhang95** [TsinghuaAI/CPM-Generate#26]
现在只有v2版本的模型可以下载，模型参数和generate文件默认参数不一致，导致读入的时候产生问题。请修改默认参数或者提供多个版本的模型下载？

**Comment by zzy14** [comment]
我们测试是没有问题的，您可以具体说一下读入时产生的问题吗？

**Comment by mikezhang95** [comment]
不好意思打扰了，我是直接用的arguments.py 里面的默认参数，没有使用scripts/generate_text.sh里面的参数。另外其他版本的模型会开源吗？

**Comment by mikezhang95** [comment]
另外，只用模型预测仍然需要占用7GB显存？有没有办法可以让显存使用少一些

**Comment by zzy14** [comment]
显存使用感觉基本压到最小了，其他规模的模型也计划开源，但是效果会比大的差比较多。

**Comment by mikezhang95** [comment]
好的，感谢！
