### ISSUE TITLE
生成数据时，随机采样的策略？如何保证相对高些的质量？

### ISSUE THREAD

**Issue by kunpeng199494** [TsinghuaAI/CPM-Generate#27]
看到作者回答说，在生成数据时，未采用最高概率作为预测结果，而进行了随机采样。所以想请教下，采样策略和依据？

**Comment by tuxchow** [comment]
因为预训练语言生成模型采用 greedy search 生成时会出现生成质量退化的问题，所以目前普遍做法是采用 top-k 或者 top-p 采样的方法进行生成，详情可以参考论文 [The Curious Case of Neural Text Degeneration](https://arxiv.org/abs/1904.09751) 。
