### ISSUE TITLE
从头开始训练需要怎么调整

### ISSUE THREAD

**Issue by zhenhao-huang** [TsinghuaAI/CPM-Generate#28]
用大概二十多g的显存(每张大概8-12g)从头训练，是否可行？需要修改什么配置

**Comment by zzy14** [comment]
看训练多大规模的模型了，我们这个模型当时是使用64块V100 32GB训练的。

**Comment by zhenhao-huang** [comment]
好吧，谢谢回复

**Comment by zhenhao-huang** [comment]
> 看训练多大规模的模型了，我们这个模型当时是使用64块V100 32GB训练的。

好吧，谢谢回复
