### ISSUE TITLE
按照readme中有关zero-shot的描述，当前主分支script文件夹下缺少对应的脚本

### ISSUE THREAD

**Issue by uk9921** [TsinghuaAI/CPM-Generate#40]
readme：
# OCNLI
bash scripts/zero-shot-ocnli.sh /path/to/CPM /path/to/dataset
# TNEWS
bash scripts/zero-shot-tnews.sh /path/to/CPM /path/to/dataset
# IFLYTEK
bash scripts/zero-shot-iflytek.sh /path/to/CPM /path/to/dataset

scripts tree：
CPM-Generate(main*) » tree ./scripts                                                                                                                           
./scripts
├── finetune.sh
├── generate_text.sh
├── generate_text_cpu.sh
├── generate_text_single.sh
├── merge_mp.sh
└── preprocess_data.sh

**Comment by zzy14** [comment]
已更新，感谢提醒！
