### ISSUE TITLE
模型无法下载

### ISSUE THREAD

**Issue by leecuijiao** [TsinghuaAI/CPM-Generate#5]
注册后无法下载模型，每次都跳转到https://cpm.baai.ac.cn/?fail 页面，能帮忙看下是什么原因吗

**Comment by Green-li** [comment]
我也无法下载模型，而且按照方法清除Cookie之后，还是一样的情况。
浏览器：Chrome 版本 84.0.4147.135（正式版本） （64 位）

**Comment by Green-li** [comment]
> 我也无法下载模型，而且按照方法清除Cookie之后，还是一样的情况。
> 浏览器：Chrome 版本 84.0.4147.135（正式版本） （64 位）

已经去除登录限制，可以下载了。

**Comment by leecuijiao** [comment]
已经去除登陆限制，可以下载了
