### ISSUE TITLE
论文问题

### ISSUE THREAD

**Issue by jieli4970** [TsinghuaAI/CPM-Generate#7]
请问readme里面挂的论文发布了吗，google了下没找到呢

**Comment by zzy14** [comment]
正在整理，会在近期挂到arxiv，感谢您的关注！

**Comment by zzy14** [comment]
我们的技术报告已经公开了，地址在[link](https://arxiv.org/abs/2012.00413)~

**Comment by jieli4970** [comment]
感谢





------------------ 原始邮件 ------------------
发件人: Zhengyan Zhang <notifications@github.com&gt;
发送时间: 2020年12月4日 10:27
收件人: TsinghuaAI/CPM-Generate <CPM-Generate@noreply.github.com&gt;
抄送: jieli4970 <819124280@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[TsinghuaAI/CPM-Generate] 论文问题 (#7)






我们的技术报告已经公开了，地址在link~
