### ISSUE TITLE
请问如何使用预训练的模型微调到其他任务

### ISSUE THREAD

**Issue by MrRace** [TsinghuaAI/CPM-Generate#9]
你好，
目前文档只有文本生成任务的example，请问会放出用以其他任务(问答、分类等)的example吗？谢谢！

**Comment by zzy14** [comment]
参考 #8.

**Comment by zmingshi** [comment]
@zzy14 您好，麻烦问下，如果想用在短文本生成，finetune 代码有可以参考哪些呢？1台8卡v100 可以 finetune 生成任务吗？

**Comment by zzy14** [comment]
可以参考 https://github.com/TsinghuaAI/CPM-Finetune ，1台我估计应该是没问题的。
